import { jsPDF } from "jspdf";

interface PredictionResult {
  verdict: "spam" | "ham";
  confidence: number;
  keywords: string[];
}

interface RiskSummary {
  level: "critical" | "high" | "medium" | "low";
  score: number;
  description: string;
}

interface Recommendation {
  title: string;
  description: string;
  icon: string;
}

export function generateSpamDetectionPDF(
  message: string,
  prediction: PredictionResult,
  riskSummary: RiskSummary,
  recommendations: Recommendation[]
): Buffer {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("SPAM MESSAGE DETECTION REPORT", margin, yPosition);
  yPosition += 10;

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 5;

  // Generated date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "numeric",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
  doc.text(`Generated: ${dateStr}, ${timeStr}`, margin, yPosition);
  yPosition += 8;

  // MESSAGE CONTENT Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("MESSAGE CONTENT:", margin, yPosition);
  yPosition += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const messageLines = doc.splitTextToSize(message, maxWidth);
  doc.text(messageLines, margin, yPosition);
  yPosition += messageLines.length * 5 + 3;

  // PREDICTION RESULT Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("PREDICTION RESULT:", margin, yPosition);
  yPosition += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  const verdictText = prediction.verdict.toUpperCase();
  const confidenceText = `${(prediction.confidence * 100).toFixed(1)}%`;
  doc.text(`Verdict: ${verdictText}`, margin, yPosition);
  yPosition += 5;
  doc.text(`Confidence: ${confidenceText}`, margin, yPosition);
  yPosition += 8;

  // RISK ASSESSMENT Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("RISK ASSESSMENT:", margin, yPosition);
  yPosition += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  const riskDescription = riskSummary.description || "No risk assessment available.";
  const riskLines = doc.splitTextToSize(riskDescription, maxWidth);
  doc.text(riskLines, margin, yPosition);
  yPosition += riskLines.length * 5 + 2;

  const riskLevelText = `Risk Level: ${riskSummary.level.toUpperCase()}`;
  const riskScoreText = `Risk Score: ${riskSummary.score}/100`;
  doc.text(riskLevelText, margin, yPosition);
  yPosition += 5;
  doc.text(riskScoreText, margin, yPosition);
  yPosition += 8;

  // TOP KEYWORDS Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("TOP KEYWORDS:", margin, yPosition);
  yPosition += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  if (prediction.keywords && prediction.keywords.length > 0) {
    prediction.keywords.forEach((keyword) => {
      doc.text(`- ${keyword}`, margin + 5, yPosition);
      yPosition += 5;
    });
  } else {
    doc.text("- No keywords identified", margin + 5, yPosition);
    yPosition += 5;
  }
  yPosition += 3;

  // PERSONALIZED RECOMMENDATIONS Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("PERSONALIZED RECOMMENDATIONS:", margin, yPosition);
  yPosition += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  if (recommendations && recommendations.length > 0) {
    recommendations.forEach((rec) => {
      const recText = `${rec.icon} ${rec.title}: ${rec.description}`;
      const recLines = doc.splitTextToSize(recText, maxWidth - 10);
      doc.text(recLines, margin + 5, yPosition);
      yPosition += recLines.length * 5 + 2;
    });
  } else {
    doc.text("- No recommendations available", margin + 5, yPosition);
    yPosition += 5;
  }

  yPosition += 5;

  // Footer separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 5;

  // Footer text
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text("Report generated by Spam Message Detection System", margin, yPosition);

  // Generate PDF buffer
  return Buffer.from(doc.output("arraybuffer"));
}
